services:
  limesurvey:
    build:
      context: 6.0/apache/
      dockerfile: Dockerfile
    volumes:
      # TODO Update storage location as desired
      # - ./surveys:/var/www/html/upload/surveys
      - /data/coolify/applications/kcso8swkggw4kg84scw44ksw/surveys:/var/www/html/upload/surveys
    networks:
      - limesurvey-db
    ports:
      - "80:80"
    environment:
      - "DB_TEST_X=testing"
      - "DB_HOST=lime-db"
      # TODO set passwords
      - "DB_PASSWORD=${DB_PASSWORD}"
      - "ADMIN_PASSWORD=${ADMIN_PASSWORD}"
      # If you require an empty table prefix, use a space as the DB_TABLE_PREFIX
      - "DB_TABLE_PREFIX=ls_"
  lime-db:
    image: mariadb:11.4
    networks:
      - limesurvey-db
    environment:
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
      # TODO set passwords
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"

networks:
  limesurvey-db:
    driver: bridge
